export enum FieldType {
    SHORT_TEXT = "SHORT_TEXT",
    LONG_TEXT = "LONG_TEXT",
    DATE = "DATE",
    TIME = "TIME",
    CHECKBOX = "CHECKBOX",
    SCALE = "SCALE",
    DROPDOWN = "DROPDOWN",
    TABLE = "TABLE",
    PERFORMANCE_OBJECTIVE = "PERFORMANCE_OBJECTIVE",
    CONFIRMATION = "CONFIRMATION",
    READ_ONLY = "READ_ONLY",
    CONDITIONAL = "CONDITIONAL",
}
